dist: xenial
sudo: required

language: php

services:
  - mysql
  - postgresql
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - PHP_INI_ENV_memory_limit=512M
    - COMPOSER_MEMORY_LIMIT=4G
    - TEST_TIMEZONES=("America/New_York" "Asia/Calcutta" "UTC")

matrix:
  fast_finish: true
  include:
# 7.3
    - name: 'Unit tests'
      php: 7.3
      install:
        - travis_retry composer install --no-progress --no-interaction --no-suggest --prefer-dist
        - echo "Testing using ${TEST_TIMEZONE} timezone"
      script: php -d date.timezone=$TEST_TIMEZONE -d memory_limit=-1 vendor/bin/phpunit -c phpunit.xml

    - name: 'Kernel Behat Core tests'
      php: 7.3
      env:
        - COMPOSE_FILE="doc/docker/base-dev.yml:doc/docker/selenium.yml"
        - APP_ENV=behat
        - APP_DEBUG=1
      install: ./bin/.travis/prepare_behat.sh
      script:
        - cd "$HOME/build/ezplatform"
        - docker-compose exec --user www-data app sh -c "bin/behat --profile=core --tags=~@broken"

    - name: 'Solr 7.7.2 integration tests (using shared cores) with Redis cache pool'
      php: 7.3
      env:
        - SOLR_VERSION="7.7.2"
        - CUSTOM_CACHE_POOL="singleredis"
        - CORES_SETUP="shared"
        - SOLR_CONFIG="vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/schema.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/custom-fields-types.xml vendor/ezsystems/ezplatform-solr-search-engine/lib/Resources/config/solr/language-fieldtypes.xml"
        - JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre/"
      install:
        - ./bin/.travis/configure_redis.sh
        - sudo apt-get install openjdk-8-jdk
        - composer require --dev --no-update ezsystems/ezplatform-solr-search-engine:^3.0.0@dev
        - travis_retry composer install --no-progress --no-interaction --no-suggest --prefer-dist
        - ./vendor/ezsystems/ezplatform-solr-search-engine/bin/.travis/init_solr.sh
        - echo "Testing using ${TEST_TIMEZONE} timezone"
      script: php -d date.timezone=$TEST_TIMEZONE -d memory_limit=-1 vendor/bin/phpunit -c phpunit-integration-legacy-solr.xml

    - name: 'PostgreSQL integration tests'
      php: 7.3
      env: DB="postgresql" DATABASE="pgsql://postgres@localhost/testdb"
      install:
        - ./bin/.travis/configure_postgresql.sh
        - travis_retry composer install --no-progress --no-interaction --no-suggest --prefer-dist
        - echo "Testing using ${TEST_TIMEZONE} timezone"
      script: php -d date.timezone=$TEST_TIMEZONE -d memory_limit=-1 vendor/bin/phpunit -c phpunit-integration-legacy.xml

    - name: 'MySQL integration tests'
      php: 7.3
      env: DB="mysql" DATABASE="mysql://root@localhost/testdb"
      install:
        - ./bin/.travis/configure_mysql.sh
        - travis_retry composer install --no-progress --no-interaction --no-suggest --prefer-dist
        - echo "Testing using ${TEST_TIMEZONE} timezone"
      script: php -d date.timezone=$TEST_TIMEZONE -d memory_limit=-1 vendor/bin/phpunit -c phpunit-integration-legacy.xml

    - name: 'Code Style Check'
      php: 7.3
      install: travis_retry composer install --no-progress --no-interaction --no-suggest --prefer-dist
      script: ./bin/.travis/check_code_style.sh

# test only master, stable branches and pull requests
branches:
  only:
    - master
    - /^\d.\d+$/

# setup requirements for running unit/integration/behat tests
before_install:
  # Disable memory_limit for composer
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Disable XDebug for all jobs as we don't generate test coverage on Travis
  - phpenv config-rm xdebug.ini
  # make sure we use UTF-8 encoding
  - echo "default_charset=UTF-8" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Setup GitHub key to avoid api rate limit (pure auth read only key, no rights, for use by ezsystems repos only!)
  - composer config -g github-oauth.github.com "d0285ed5c8644f30547572ead2ed897431c1fc09"
  # Test on random timezone to detect timezone issues
  - TEST_TIMEZONE=${TEST_TIMEZONES["`shuf -i 0-2 -n 1`"]}

notifications:
  slack:
    rooms:
      - secure: "PYKf96lJCy3hK28PAkI6sB167hUwiGKl7x800Er81pXHhs6CbfVUp0Q+ojsRX8rh45hqbulQ9pzY8G1Y7JZejPJ/e3tWwXsbNSCRfB2B9XE1T5T2KGdws0ExllRsA6hC8FzC7BEId3QUNsXurGrSYgV5aCJw7B5dZliNwJmutVOTGhYkcUivKR5qrQP3Wdg+qwbslYYvJ5VaRh0O+WPlM6AnC9a88tK6yLygnG+h7j7Uc2maBeXihZoyJrjYSx8JEzk9sMh2VCTANMCek6KkxGeORsUl+GH3upHyzu9iYna3vPfGiF5Ur0XpWfjk6uZ4IHY7+H6kaxvJBbKnBcLVLji3+i8Lj/XIyuumSMfLgKVj3PQVFIpzW+jSByk1ZvY75k6LlmrcNd38t7wsNEoUUEI128GBS13SbEepp4lIpvW5iqjofHPlVS/U4B669sHDeZJRbSSxZ9oRwlT9ehPB7N6dkjSjx49LblMl7C5GU/tU9HFy4+3QFnepebhzoFZzsLsrLZc/2+OxV93rt14vn7Arnt8mgXZOJLvIu9Di0gYjgppHt6pq/tRYRo6AG7NOnMW/Vvvn3WggP8g5Z1IOmrNLUiN75AHJq4WO51Rj+FWSp2te0NEqGx8Jisr0l49ftkzC4YxTxuxnthkevy/EeUniXvgz7e2B19jF2S6jRKo="
    on_success: change
    on_failure: always
    on_pull_requests: false

# reduce depth (history) of git checkout
git:
  depth: 30
